export const site = {
  name: 'Bergedorf Apartments', telephone: '+49 1512 7606093', telephoneLink: '+4915127606093',
  address: 'Weidenbaumsweg 141', postal: '21035 Hamburg-Bergedorf',
  operator: 'Agat Management GmbH', operatorAddress: 'Ahrensburger Straße 199 · 22045 Hamburg',
  register: 'Amtsgericht Hamburg · HRB 140484', email: 'Vp@simplyfood.de',
  map: 'https://www.google.com/maps/search/?api=1&query=Weidenbaumsweg+141+21035+Hamburg'
};
export const copy = {
  de: {
    datePicker: {placeholder:'TT.MM.JJJJ',open:'Kalender öffnen',previous:'Vorheriger Monat',next:'Nächster Monat',clear:'Datum löschen',title:'Datum auswählen'},
    title: 'Bergedorf Apartments — Wohnen auf Zeit in Hamburg',
    meta: '15 komplett ausgestattete Apartments in Hamburg-Bergedorf. Eigene Küche, WLAN und Self Check-in 24/7. Jetzt Ihren Aufenthalt direkt anfragen.',
    skip: 'Zum Inhalt', nav: ['Apartments', 'Über uns', 'Lage', 'Kontakt'], contact: 'Kontakt aufnehmen', inquire: 'Aufenthalt anfragen',
    heroLabel: 'HAMBURG–BERGEDORF', heroLead: 'Ein Stück Zuhause.\nMitten in Bergedorf.',
    heroDescription: 'Komfortable Apartments für kurze und längere Aufenthalte in Hamburg. Ankommen, durchatmen, zuhause fühlen.',
    heroBody: 'Mit eigener Küche, guter Anbindung und allem, was das Leben angenehm macht.', explore: 'Apartments entdecken',
    checkLabel: 'Ankommen. Wann es Ihnen passt.', checkSmall: 'Persönlicher PIN · Schlüsselbox · 24/7',
    heroCaption: 'Komfort. Flexibilität. Ein gutes Gefühl.', photo: 'Küche und Essbereich in Bergedorf Apartments',
    catalogueLabel: 'RAUM FÜR IHREN AUFENTHALT', catalogueTitle: 'Ein Zuhause.\n15 Möglichkeiten.',
    catalogueIntro: '15 komplett ausgestattete Apartments für kurze und längere Aufenthalte. Wählen Sie Ihren Favoriten — wir kümmern uns um den Rest.',
    all: 'Alle 15 Apartments', less: 'Auswahl verkleinern', apartment: 'Apartment', gallery: 'Fotogalerie öffnen', galleryTitle: 'Einblicke in Ihr Zuhause auf Zeit',
    galleryCount: '7 echte Einblicke', galleryNote: 'Fotos eines Apartments aus unserem Haus. Die Zuordnung zu Apartment 01 dient aktuell der Vorschau.',
    standard: 'KOMFORT IN JEDEM APARTMENT', amenities: ['Eigene Küche', 'Bad mit Dusche', 'WLAN', 'TV', 'Wasch- & Trockenmöglichkeiten', 'Komplett möbliert'],
    price: 'Preis auf Anfrage', reservation: 'Nur mit vorheriger bestätigter Reservierung.', preview: 'Fotos folgen', photoSoon: 'Ihr nächstes Zuhause.',
    previewNote: 'Fotos & individuelle Details folgen', details: 'Größe & Belegung auf Anfrage', previous: 'Vorheriges Apartment', next: 'Nächstes Apartment',
    aboutLabel: 'EINFACH GUT WOHNEN', aboutTitle: 'Alles da.\nGanz bei sich.',
    aboutBody: 'Für ein paar Tage oder eine längere Zeit: Wir schaffen Raum für Ihren Alltag. Mit dem Komfort einer eigenen Wohnung und der Freiheit, Ihren Aufenthalt selbst zu gestalten.',
    aboutLink: 'Was Ihren Aufenthalt angenehm macht', benefitTitles: ['Gut verbunden.', 'Ihr eigener Rhythmus.', 'Alles für den Alltag.'],
    benefitBodies: ['S-Bahn, Busverbindungen, Einkaufsmöglichkeiten, Cafés und Restaurants in der Nähe. Die Hamburger Innenstadt ist bequem mit öffentlichen Verkehrsmitteln erreichbar.', 'Kochen, arbeiten, entspannen. Ihre eigene Küche und Ihr eigenes Badezimmer geben Ihnen die Freiheit, sich ganz wie zuhause zu fühlen.', 'WLAN, TV, Möblierung sowie Wasch- und Trockenmöglichkeiten. Weniger organisieren, mehr Zeit für Ihren Aufenthalt.'],
    benefitPrev: 'Vorheriger Vorteil', benefitNext: 'Nächster Vorteil',
    checkTitle: 'Ihre Ankunft.\nIhre Zeit.', checkHeading: 'Self Check-in 24/7',
    checkBody: 'Bei uns gibt es keine klassische Rezeption. Vor Ihrer Anreise erhalten Sie einen persönlichen PIN-Code für die Schlüsselbox. So können Sie selbstständig einchecken — 24 Stunden am Tag, 7 Tage die Woche.',
    checkSteps: ['Aufenthalt reservieren', 'Persönlichen PIN erhalten', 'Ankommen & einchecken'],
    locationLabel: 'HAMBURG, MIT MEHR RUHE', locationTitle: 'Bergedorf.\nGut angekommen.',
    locationBody: 'Eine gute Verbindung zur Stadt und alles Wichtige in Ihrer Nähe. Unsere Apartments liegen am Weidenbaumsweg in Hamburg-Bergedorf.',
    map: 'Route planen', mapNote: 'Öffnet Google Maps in einem neuen Tab.', mapGraphic: 'Schematische Darstellung der Lage in Hamburg-Bergedorf, keine maßstabsgetreue Karte',
    faqLabel: 'GUT ZU WISSEN', faqTitle: 'Vor der Anreise.',
    faqs: [
      ['Wie funktioniert der Check-in?', 'Nach Ihrer bestätigten Reservierung erhalten Sie vor der Anreise Ihren persönlichen PIN-Code für die Schlüsselbox. Sie können rund um die Uhr selbstständig einchecken. Eine klassische Rezeption gibt es nicht.'],
      ['Sind längere Aufenthalte möglich?', 'Ja. Unsere Apartments sind für kurze und längere Aufenthalte geeignet. Teilen Sie uns Ihren gewünschten Zeitraum mit, damit wir Verfügbarkeit und Konditionen prüfen können.'],
      ['Was ist im Apartment vorhanden?', 'Jedes Apartment hat eine eigene Küche und ein Badezimmer und ist komplett möbliert. WLAN, TV sowie Wasch- und Trockenmöglichkeiten gehören zur Ausstattung. Die individuelle Aufteilung erfragen Sie direkt bei uns.'],
      ['Ist meine Anfrage bereits eine Buchung?', 'Nein. Eine Anfrage ist unverbindlich. Der Aufenthalt ist erst nach unserer ausdrücklichen Reservierungsbestätigung möglich. Preis und Verfügbarkeit stimmen wir direkt mit Ihnen ab.']
    ],
    contactLabel: 'WIR FREUEN UNS AUF SIE', contactTitle: 'Ein guter Aufenthalt\nbeginnt mit einem Hallo.',
    contactBody: 'Fragen, Wünsche oder schon konkrete Pläne? Erzählen Sie uns davon. Wir helfen Ihnen gerne weiter.', phoneLabel: 'Persönlich für Sie da', hours: 'Telefonisch 9:00–17:00 Uhr', call: 'Jetzt anrufen',
    contactHint: 'Keine Sofortbuchung. Persönlicher Kontakt.', formTitle: 'Ihr Aufenthalt in Bergedorf', formIntro: 'Unverbindlich anfragen. Wir prüfen Preis und Verfügbarkeit für Ihren Zeitraum.',
    fields: { name: 'Ihr Name', email: 'E-Mail-Adresse', phone: 'Telefon', arrival: 'Anreise', departure: 'Abreise', apartment: 'Gewünschtes Apartment', message: 'Was können wir für Sie tun?' },
    optional: 'optional', noPreference: 'Keine Präferenz', nameHint: 'Vor- und Nachname', messageHint: 'Zeitraum, Anzahl der Gäste, besondere Wünsche …',
    consent: 'Ich willige in die Verarbeitung meiner Angaben zur Bearbeitung dieser Anfrage ein.', consentLink: 'Einwilligung lesen', privacyLink: 'Datenschutz',
    submit: 'Anfrage senden', demoSubmit: '', submitting: 'Wird gesendet …',
    demo: '',
    demoValid: '',
    success: 'Vielen Dank! Ihre Anfrage wurde gesendet. Wir melden uns bei Ihnen. Die Reservierung ist noch nicht bestätigt.',
    error: 'Die Anfrage konnte nicht gesendet werden. Bitte versuchen Sie es später oder rufen Sie uns an.',
    errors: { name: 'Bitte geben Sie Ihren Namen ein (2–100 Zeichen).', email: 'Bitte geben Sie eine gültige E-Mail-Adresse ein.', phone: 'Bitte prüfen Sie Ihre Telefonnummer.', date: 'Bitte wählen Sie ein gültiges Datum ab heute.', dateOrder: 'Die Abreise muss nach der Anreise liegen.', datePair: 'Bitte geben Sie Anreise und Abreise an.', consent: 'Bitte erteilen Sie die separate Einwilligung.', message: 'Bitte verwenden Sie höchstens 2.000 Zeichen.', apartment: 'Bitte wählen Sie ein Apartment aus der Liste.' },
    footerTag: 'Komfort. Flexibilität. Zuhause auf Zeit.', footerLegal: 'Betreiber', copyright: 'Alle Rechte vorbehalten.', imprint: 'Impressum', privacy: 'Datenschutz', cookies: 'Cookie-Hinweise', cookieSettings: 'Cookie-Einstellungen', back: 'Zurück zur Startseite', close: 'Schließen',
    cookieTitle: 'Ein kleiner Hinweis zum Datenschutz.', cookieBody: 'Keine Werbung, kein Tracking. Wir verwenden nur lokale Einstellungen und bei aktivierter Anfrage technisch notwendige Sicherheitsfunktionen.',
    cookieAccept: 'Verstanden', cookieNecessary: 'Nur notwendige', cookieMore: 'Einstellungen', cookieSettingsTitle: 'Ihre Privatsphäre, Ihre Entscheidung.',
    cookieSettingsBody: 'Auf dieser Website gibt es keine Analyse- oder Marketing-Cookies. Schriftarten und Fotos werden lokal geladen. Karten öffnen erst nach Ihrem Klick auf einer externen Seite.',
    cookieRequired: 'Technisch notwendig', cookieRequiredBody: 'Speichert diesen Hinweis für bis zu 180 Tage; eine aktivierte Kontaktanfrage nutzt eine kurzlebige Sicherheitssitzung.', always: 'Immer aktiv', cookieSave: 'Einstellungen speichern',
    legalNote: 'Vorschau — Veröffentlichung erst nach Ergänzung und Freigabe der tatsächlichen Betreiber-, Kontakt- und Hostingangaben.',
    imageAlts: { 'twin-room': 'Helles Zimmer mit zwei Einzelbetten und olivgrüner Wand', kitchen: 'Eigene Küche und Esstisch mit hellen Holzstühlen', 'living-room': 'Wohn- und Essbereich mit großen Fenstern', 'single-room': 'Separates Schlafzimmer mit Einzelbett', bathroom: 'Badezimmer mit Dusche und Handtuchheizkörper', 'bathroom-detail': 'Waschbecken, Spiegel und Handtücher im Badezimmer', hallway: 'Eingangsbereich mit Spiegel und Garderobe' }
  },
};
